[theme]
primaryColor = "#1976D2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#1E1E1E"
font = "sans-serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false