[theme]
primaryColor = "#1976D2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#1E1E1E"
font = "sans serif"

[server]
maxUploadSize = 200

[global]
showWarningOnDirectExecution = false